const MESSAGE_STATUS = []
MESSAGE_STATUS['UNSEEN'] = 0
MESSAGE_STATUS['SEEN'] = 1

const ROOM_TYPE = []
ROOM_TYPE['PRIVATE'] = 0
ROOM_TYPE['GROUP'] = 1

const ACCOUNT_STATUS = []
ACCOUNT_STATUS['OFFLINE'] = 0
ACCOUNT_STATUS['ONLINE'] = 1

const ENUM = {
    MESSAGE_STATUS,
    ROOM_TYPE,
    ACCOUNT_STATUS
}

export default ENUM